
name: my demo

on:
  push:
    branches: ["master"]


jobs:
  demojob:
    runs-on: ubuntu-latest
    steps:
    
    - name: 'cloning repo'
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
    -name: 'listing files'
      run: ls
