
name: my demo

on:
  # push:
  #   branches: ["master"]
  pull_request: 
    types: 
      - opened
      - edited
      - reopened
      - synchronize
  workflow_dispatch: 
  workflow_run:
    workflows: Build and Push Docker Image
jobs:
  demojob:
    runs-on: ubuntu-latest
    steps:
      - name: display
        run: echo "hello world"
       
